package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolLesson generated by hbm2java
 */
@SequenceGenerator(name = "SEQ_LESSON_ID", sequenceName = "SEQ_SCHOOL_LESSON")
public class SchoolLesson  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator = "SEQ_LESSON_ID", strategy = GenerationType.SEQUENCE)
     private Integer lessonId;
     private SchoolLessonNumber schoolLessonNumber;
     private SchoolClass schoolClass;
     private SchoolTeacher schoolTeacher;
     private SchoolSubject schoolSubject;
     private Integer dayId;
     private String room;
     private Set schoolMessages = new HashSet(0);

    public SchoolLesson() {
    }

	
    public SchoolLesson(Integer lessonId, Integer dayId) {
        this.lessonId = lessonId;
        this.dayId = dayId;
    }
    public SchoolLesson(Integer lessonId, SchoolLessonNumber schoolLessonNumber, SchoolClass schoolClass, SchoolTeacher schoolTeacher, SchoolSubject schoolSubject, Integer dayId, String room, Set schoolMessages) {
       this.lessonId = lessonId;
       this.schoolLessonNumber = schoolLessonNumber;
       this.schoolClass = schoolClass;
       this.schoolTeacher = schoolTeacher;
       this.schoolSubject = schoolSubject;
       this.dayId = dayId;
       this.room = room;
       this.schoolMessages = schoolMessages;
    }
   
    public Integer getLessonId() {
        return this.lessonId;
    }
    
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }
    public SchoolLessonNumber getSchoolLessonNumber() {
        return this.schoolLessonNumber;
    }
    
    public void setSchoolLessonNumber(SchoolLessonNumber schoolLessonNumber) {
        this.schoolLessonNumber = schoolLessonNumber;
    }
    public SchoolClass getSchoolClass() {
        return this.schoolClass;
    }
    
    public void setSchoolClass(SchoolClass schoolClass) {
        this.schoolClass = schoolClass;
    }
    public SchoolTeacher getSchoolTeacher() {
        return this.schoolTeacher;
    }
    
    public void setSchoolTeacher(SchoolTeacher schoolTeacher) {
        this.schoolTeacher = schoolTeacher;
    }
    public SchoolSubject getSchoolSubject() {
        return this.schoolSubject;
    }
    
    public void setSchoolSubject(SchoolSubject schoolSubject) {
        this.schoolSubject = schoolSubject;
    }
    public Integer getDayId() {
        return this.dayId;
    }
    
    public void setDayId(Integer dayId) {
        this.dayId = dayId;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }
    public Set getSchoolMessages() {
        return this.schoolMessages;
    }
    
    public void setSchoolMessages(Set schoolMessages) {
        this.schoolMessages = schoolMessages;
    }




}


