package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolSubject generated by hbm2java
 */
@SequenceGenerator(name="SEQ_SUBJECT_ID", sequenceName="SEQ_SCHOOL_SUBJECT")
public class SchoolSubject  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator="SEQ_SUBJECT_ID", strategy = GenerationType.SEQUENCE)
     private Integer subjectId;
     private String subjectName;
     private Set schoolLessons = new HashSet(0);
     private Set schoolSubjectTeachers = new HashSet(0);

    public SchoolSubject() {
    }

	
    public SchoolSubject(Integer subjectId, String subjectName) {
        this.subjectId = subjectId;
        this.subjectName = subjectName;
    }
    public SchoolSubject(Integer subjectId, String subjectName, Set schoolLessons, Set schoolSubjectTeachers) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.schoolLessons = schoolLessons;
       this.schoolSubjectTeachers = schoolSubjectTeachers;
    }
   
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Set getSchoolLessons() {
        return this.schoolLessons;
    }
    
    public void setSchoolLessons(Set schoolLessons) {
        this.schoolLessons = schoolLessons;
    }
    public Set getSchoolSubjectTeachers() {
        return this.schoolSubjectTeachers;
    }
    
    public void setSchoolSubjectTeachers(Set schoolSubjectTeachers) {
        this.schoolSubjectTeachers = schoolSubjectTeachers;
    }




}


