package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA

/**
 * SchoolLessonNumberId generated by hbm2java
 */
public class SchoolLessonNumberId  implements java.io.Serializable {


     private Integer schoolId;
     private Integer lessonNumberId;

    public SchoolLessonNumberId() {
    }

    public SchoolLessonNumberId(Integer schoolId, Integer lessonNumberId) {
       this.schoolId = schoolId;
       this.lessonNumberId = lessonNumberId;
    }
   
    public Integer getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
    public Integer getLessonNumberId() {
        return this.lessonNumberId;
    }
    
    public void setLessonNumberId(Integer lessonNumberId) {
        this.lessonNumberId = lessonNumberId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SchoolLessonNumberId) ) return false;
		 SchoolLessonNumberId castOther = ( SchoolLessonNumberId ) other; 
         
		 return ( (this.getSchoolId()==castOther.getSchoolId()) || ( this.getSchoolId()!=null && castOther.getSchoolId()!=null && this.getSchoolId().equals(castOther.getSchoolId()) ) )
 && ( (this.getLessonNumberId()==castOther.getLessonNumberId()) || ( this.getLessonNumberId()!=null && castOther.getLessonNumberId()!=null && this.getLessonNumberId().equals(castOther.getLessonNumberId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSchoolId() == null ? 0 : this.getSchoolId().hashCode() );
         result = 37 * result + ( getLessonNumberId() == null ? 0 : this.getLessonNumberId().hashCode() );
         return result;
   }   


}


