package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * School generated by hbm2java
 */
@SequenceGenerator(name = "SEQ_SCHOOL_ID", sequenceName = "SEQ_SCHOOL")
public class School  implements java.io.Serializable {

     @Id
     @GeneratedValue(generator = "SEQ_SCHOOL_ID", strategy = GenerationType.SEQUENCE)
     private Integer schoolId;
     private String schoolName;
     private String schoolAddress;
     private String schoolEmail;
     private String schoolPhoneNumber;
     private String schoolWebsite;
     private Set schoolUsers = new HashSet(0);
     private Set schoolClasses = new HashSet(0);
     private Set schoolTeachers = new HashSet(0);

    public School() {
    }

	
    public School(Integer schoolId, String schoolName) {
        this.schoolId = schoolId;
        this.schoolName = schoolName;
    }
    public School(Integer schoolId, String schoolName, String schoolAddress, String schoolEmail, String schoolPhoneNumber, String schoolWebsite, Set schoolUsers, Set schoolClasses, Set schoolTeachers) {
       this.schoolId = schoolId;
       this.schoolName = schoolName;
       this.schoolAddress = schoolAddress;
       this.schoolEmail = schoolEmail;
       this.schoolPhoneNumber = schoolPhoneNumber;
       this.schoolWebsite = schoolWebsite;
       this.schoolUsers = schoolUsers;
       this.schoolClasses = schoolClasses;
       this.schoolTeachers = schoolTeachers;
    }
   
    public Integer getSchoolId() {
        return this.schoolId;
    }
    
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }
    public String getSchoolAddress() {
        return this.schoolAddress;
    }
    
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress;
    }
    public String getSchoolEmail() {
        return this.schoolEmail;
    }
    
    public void setSchoolEmail(String schoolEmail) {
        this.schoolEmail = schoolEmail;
    }
    public String getSchoolPhoneNumber() {
        return this.schoolPhoneNumber;
    }
    
    public void setSchoolPhoneNumber(String schoolPhoneNumber) {
        this.schoolPhoneNumber = schoolPhoneNumber;
    }
    public String getSchoolWebsite() {
        return this.schoolWebsite;
    }
    
    public void setSchoolWebsite(String schoolWebsite) {
        this.schoolWebsite = schoolWebsite;
    }
    public Set getSchoolUsers() {
        return this.schoolUsers;
    }
    
    public void setSchoolUsers(Set schoolUsers) {
        this.schoolUsers = schoolUsers;
    }
    public Set getSchoolClasses() {
        return this.schoolClasses;
    }
    
    public void setSchoolClasses(Set schoolClasses) {
        this.schoolClasses = schoolClasses;
    }
    public Set getSchoolTeachers() {
        return this.schoolTeachers;
    }
    
    public void setSchoolTeachers(Set schoolTeachers) {
        this.schoolTeachers = schoolTeachers;
    }




}


