package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolUser generated by hbm2java
 */
@SequenceGenerator(name="SEQ_USER_ID", sequenceName="SEQ_SCHOOL_USER")
public class SchoolUser  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator="SEQ_USER_ID", strategy = GenerationType.SEQUENCE)
     private Integer userId;
     private School school;
     private Integer userPrivilege;
     private String login;
     private String pass;

    public SchoolUser() {
    }

	
    public SchoolUser(Integer userId, String login, String pass) {
        this.userId = userId;
        this.login = login;
        this.pass = pass;
    }
    public SchoolUser(Integer userId, School school, Integer userPrivilege, String login, String pass) {
       this.userId = userId;
       this.school = school;
       this.userPrivilege = userPrivilege;
       this.login = login;
       this.pass = pass;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public School getSchool() {
        return this.school;
    }
    
    public void setSchool(School school) {
        this.school = school;
    }
    public Integer getUserPrivilege() {
        return this.userPrivilege;
    }
    
    public void setUserPrivilege(Integer userPrivilege) {
        this.userPrivilege = userPrivilege;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


