package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolClass generated by hbm2java
 */
@SequenceGenerator(name = "SEQ_CLASS_ID", sequenceName = "SEQ_SCHOOL_CLASS")
public class SchoolClass  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator = "SEQ_CLASS_ID", strategy = GenerationType.SEQUENCE)
     private Integer classId;
     private SchoolTeacher schoolTeacher;
     private School school;
     private String className;
     private Set schoolLessons = new HashSet(0);

    public SchoolClass() {
    }

	
    public SchoolClass(Integer classId) {
        this.classId = classId;
    }
    public SchoolClass(Integer classId, SchoolTeacher schoolTeacher, School school, String className, Set schoolLessons) {
       this.classId = classId;
       this.schoolTeacher = schoolTeacher;
       this.school = school;
       this.className = className;
       this.schoolLessons = schoolLessons;
    }
   
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public SchoolTeacher getSchoolTeacher() {
        return this.schoolTeacher;
    }
    
    public void setSchoolTeacher(SchoolTeacher schoolTeacher) {
        this.schoolTeacher = schoolTeacher;
    }
    public School getSchool() {
        return this.school;
    }
    
    public void setSchool(School school) {
        this.school = school;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Set getSchoolLessons() {
        return this.schoolLessons;
    }
    
    public void setSchoolLessons(Set schoolLessons) {
        this.schoolLessons = schoolLessons;
    }




}


