package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SchoolLessonNumber generated by hbm2java
 */
public class SchoolLessonNumber  implements java.io.Serializable {


     private SchoolLessonNumberId id;
     private String startTime;
     private String endTime;
     private Set schoolLessons = new HashSet(0);

    public SchoolLessonNumber() {
    }

	
    public SchoolLessonNumber(SchoolLessonNumberId id, String startTime, String endTime) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
    }
    public SchoolLessonNumber(SchoolLessonNumberId id, String startTime, String endTime, Set schoolLessons) {
       this.id = id;
       this.startTime = startTime;
       this.endTime = endTime;
       this.schoolLessons = schoolLessons;
    }
   
    public SchoolLessonNumberId getId() {
        return this.id;
    }
    
    public void setId(SchoolLessonNumberId id) {
        this.id = id;
    }
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
    public Set getSchoolLessons() {
        return this.schoolLessons;
    }
    
    public void setSchoolLessons(Set schoolLessons) {
        this.schoolLessons = schoolLessons;
    }




}


