package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolTeacher generated by hbm2java
 */
@SequenceGenerator(name="SEQ_TEACHER_ID", sequenceName="SEQ_SCHOOL_TEACHER")
public class SchoolTeacher  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator="SEQ_TEACHER_ID", strategy = GenerationType.SEQUENCE)
     private Integer teacherId;
     private School school;
     private String teacherName;
     private String teacherSurname;
     private Set schoolSubjectTeachers = new HashSet(0);
     private Set schoolClasses = new HashSet(0);
     private Set schoolLessons = new HashSet(0);
     private Set schoolMessages = new HashSet(0);

    public SchoolTeacher() {
    }

	
    public SchoolTeacher(Integer teacherId, String teacherName, String teacherSurname) {
        this.teacherId = teacherId;
        this.teacherName = teacherName;
        this.teacherSurname = teacherSurname;
    }
    public SchoolTeacher(Integer teacherId, School school, String teacherName, String teacherSurname, Set schoolSubjectTeachers, Set schoolClasses, Set schoolLessons, Set schoolMessages) {
       this.teacherId = teacherId;
       this.school = school;
       this.teacherName = teacherName;
       this.teacherSurname = teacherSurname;
       this.schoolSubjectTeachers = schoolSubjectTeachers;
       this.schoolClasses = schoolClasses;
       this.schoolLessons = schoolLessons;
       this.schoolMessages = schoolMessages;
    }
   
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
    public School getSchool() {
        return this.school;
    }
    
    public void setSchool(School school) {
        this.school = school;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    public String getTeacherSurname() {
        return this.teacherSurname;
    }
    
    public void setTeacherSurname(String teacherSurname) {
        this.teacherSurname = teacherSurname;
    }
    public Set getSchoolSubjectTeachers() {
        return this.schoolSubjectTeachers;
    }
    
    public void setSchoolSubjectTeachers(Set schoolSubjectTeachers) {
        this.schoolSubjectTeachers = schoolSubjectTeachers;
    }
    public Set getSchoolClasses() {
        return this.schoolClasses;
    }
    
    public void setSchoolClasses(Set schoolClasses) {
        this.schoolClasses = schoolClasses;
    }
    public Set getSchoolLessons() {
        return this.schoolLessons;
    }
    
    public void setSchoolLessons(Set schoolLessons) {
        this.schoolLessons = schoolLessons;
    }
    public Set getSchoolMessages() {
        return this.schoolMessages;
    }
    
    public void setSchoolMessages(Set schoolMessages) {
        this.schoolMessages = schoolMessages;
    }




}


