package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolMessage generated by hbm2java
 */
@SequenceGenerator(name="SEQ_MESSAGE_ID", sequenceName="SEQ_SCHOOL_MESSAGE")
public class SchoolMessage  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator="SEQ_MESSAGE_ID", strategy = GenerationType.SEQUENCE)
     private Integer messageId;
     private SchoolLesson schoolLesson;
     private SchoolTeacher schoolTeacher;
     private Date messageDate;
     private String text;

    public SchoolMessage() {
    }

	
    public SchoolMessage(Integer messageId, Date messageDate, String text) {
        this.messageId = messageId;
        this.messageDate = messageDate;
        this.text = text;
    }
    public SchoolMessage(Integer messageId, SchoolLesson schoolLesson, SchoolTeacher schoolTeacher, Date messageDate, String text) {
       this.messageId = messageId;
       this.schoolLesson = schoolLesson;
       this.schoolTeacher = schoolTeacher;
       this.messageDate = messageDate;
       this.text = text;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public SchoolLesson getSchoolLesson() {
        return this.schoolLesson;
    }
    
    public void setSchoolLesson(SchoolLesson schoolLesson) {
        this.schoolLesson = schoolLesson;
    }
    public SchoolTeacher getSchoolTeacher() {
        return this.schoolTeacher;
    }
    
    public void setSchoolTeacher(SchoolTeacher schoolTeacher) {
        this.schoolTeacher = schoolTeacher;
    }
    public Date getMessageDate() {
        return this.messageDate;
    }
    
    public void setMessageDate(Date messageDate) {
        this.messageDate = messageDate;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


