package dbclass;
// Generated 2012-02-13 14:15:24 by Hibernate Tools 3.2.1.GA


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * SchoolSubject generated by hbm2java
 */
@SequenceGenerator(name="SEQ_SUBJECT_TEACHER_ID", sequenceName="SEQ_SCHOOL_SUBJECT_TEACHER")
public class SchoolSubjectTeacher  implements java.io.Serializable {

    @Id
    @GeneratedValue(generator="SEQ_SUBJECT_TEACHER_ID", strategy = GenerationType.SEQUENCE)
     private Integer subjectTeacherId;
     private SchoolTeacher schoolTeacher;
     private SchoolSubject schoolSubject;

    public SchoolSubjectTeacher() {
    }

	
    public SchoolSubjectTeacher(Integer subjectTeacherId) {
        this.subjectTeacherId = subjectTeacherId;
    }
    public SchoolSubjectTeacher(Integer subjectTeacherId, SchoolTeacher schoolTeacher, SchoolSubject schoolSubject) {
       this.subjectTeacherId = subjectTeacherId;
       this.schoolTeacher = schoolTeacher;
       this.schoolSubject = schoolSubject;
    }
   
    public Integer getSubjectTeacherId() {
        return this.subjectTeacherId;
    }
    
    public void setSubjectTeacherId(Integer subjectTeacherId) {
        this.subjectTeacherId = subjectTeacherId;
    }
    public SchoolTeacher getSchoolTeacher() {
        return this.schoolTeacher;
    }
    
    public void setSchoolTeacher(SchoolTeacher schoolTeacher) {
        this.schoolTeacher = schoolTeacher;
    }
    public SchoolSubject getSchoolSubject() {
        return this.schoolSubject;
    }
    
    public void setSchoolSubject(SchoolSubject schoolSubject) {
        this.schoolSubject = schoolSubject;
    }




}


